sudo: required
language: java
jdk:
  - openjdk8

services:
  - docker

script:
  - docker-compose up -d

after_success:
  - docker build -t kpadania/school-service ./school-service
  - docker build -t kpadania/school-ui ./school-ui
  - docker build -t kpadania/config ./config
  - docker build -t kpadania/discovery ./discovery
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kpadania/school-service
  - docker push kpadania/school-ui
  - docker push kpadania/config
  - docker push kpadania/discovery

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "microservices-docker"
  env: "MicroservicesDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-830990676668"
  bucket_path: "microservices-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"